In [1]:
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline

In [6]:
full_dataset= pd.read_csv("0320_diabetes_clean.csv")

In [7]:
full_dataset.head()

,Unnamed: 0,encounter_id,patient_nbr,race,gender,age,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,...,insulin,change,diabetesMed,readmitted,admissionType,dischargeDisposition,admissionSource,diag_1_cat,diag_2_cat,diag_3_cat
0,1,149190,55629189,Caucasian,Female,[10-20),3,?,?,59,...,Up,Ch,Yes,No,Emergency,Discharged to home,Emergency Room,Neoplasms,Diabetes,Neoplasms
1,2,64410,86047875,AfricanAmerican,Female,[20-30),2,?,?,11,...,No,No,Yes,No,Emergency,Discharged to home,Emergency Room,Other,Diabetes,Other
2,3,500364,82442376,Caucasian,Male,[30-40),2,?,?,44,...,Up,Ch,Yes,No,Emergency,Discharged to home,Emergency Room,Other,Diabetes,Circulatory
3,4,16680,42519267,Caucasian,Male,[40-50),1,?,?,51,...,Steady,Ch,Yes,No,Emergency,Discharged to home,Emergency Room,Neoplasms,Neoplasms,Diabetes
4,5,35754,82637451,Caucasian,Male,[50-60),3,?,?,31,...,Steady,No,Yes,No,Urgent,Discharged to home,Clinic Referral,Circulatory,Circulatory,Diabetes

# remove column payer_code
since it contains a large number of missing data, and we believe it does not effect the response (readmission)

In [8]:
full_dataset.drop(['payer_code'], axis = 1, inplace = True)

In [9]:
full_dataset.shape

(98594, 34)

### Based on the paper, remove " dischargeDisposition"="discharge to hospice" 
* 396 rows + 368 rows dropped

In [12]:
full_dataset.drop(full_dataset[full_dataset['dischargeDisposition']=="Hospice / home"].index,axis=0,inplace=True)

full_dataset.drop(full_dataset[full_dataset['dischargeDisposition']=="Hospice / medical facility" ].index,axis=0,inplace=True)

In [13]:
full_dataset.shape

(97825, 34)

### drop "encounter_id" and "patient_nbr" column
* these are just  unique IDs for the patients

In [14]:
full_dataset.drop(['encounter_id'], axis = 1, inplace = True)
full_dataset.drop(['patient_nbr'], axis = 1, inplace = True)

### drop rows  "race" =="?"
* 2152 rows dropped

In [16]:
full_dataset.drop(full_dataset[full_dataset['race']=="?"].index,axis=0,inplace=True)

In [17]:
full_dataset.shape

(95673, 32)

In [25]:
full_dataset.to_csv("0406_diabetes_clean.csv")

In [18]:
full_dataset.head()

,Unnamed: 0,race,gender,age,time_in_hospital,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,...,insulin,change,diabetesMed,readmitted,admissionType,dischargeDisposition,admissionSource,diag_1_cat,diag_2_cat,diag_3_cat
0,1,Caucasian,Female,[10-20),3,?,59,0,18,0,...,Up,Ch,Yes,No,Emergency,Discharged to home,Emergency Room,Neoplasms,Diabetes,Neoplasms
1,2,AfricanAmerican,Female,[20-30),2,?,11,5,13,2,...,No,No,Yes,No,Emergency,Discharged to home,Emergency Room,Other,Diabetes,Other
2,3,Caucasian,Male,[30-40),2,?,44,1,16,0,...,Up,Ch,Yes,No,Emergency,Discharged to home,Emergency Room,Other,Diabetes,Circulatory
3,4,Caucasian,Male,[40-50),1,?,51,0,8,0,...,Steady,Ch,Yes,No,Emergency,Discharged to home,Emergency Room,Neoplasms,Neoplasms,Diabetes
4,5,Caucasian,Male,[50-60),3,?,31,6,16,0,...,Steady,No,Yes,No,Urgent,Discharged to home,Clinic Referral,Circulatory,Circulatory,Diabetes

### drop column "unnamed"

In [23]:
full_dataset.drop('Unnamed: 0', axis=1, inplace=True)

In [24]:
full_dataset.head()

,race,gender,age,time_in_hospital,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,...,insulin,change,diabetesMed,readmitted,admissionType,dischargeDisposition,admissionSource,diag_1_cat,diag_2_cat,diag_3_cat
0,Caucasian,Female,[10-20),3,?,59,0,18,0,0,...,Up,Ch,Yes,No,Emergency,Discharged to home,Emergency Room,Neoplasms,Diabetes,Neoplasms
1,AfricanAmerican,Female,[20-30),2,?,11,5,13,2,0,...,No,No,Yes,No,Emergency,Discharged to home,Emergency Room,Other,Diabetes,Other
2,Caucasian,Male,[30-40),2,?,44,1,16,0,0,...,Up,Ch,Yes,No,Emergency,Discharged to home,Emergency Room,Other,Diabetes,Circulatory
3,Caucasian,Male,[40-50),1,?,51,0,8,0,0,...,Steady,Ch,Yes,No,Emergency,Discharged to home,Emergency Room,Neoplasms,Neoplasms,Diabetes
4,Caucasian,Male,[50-60),3,?,31,6,16,0,0,...,Steady,No,Yes,No,Urgent,Discharged to home,Clinic Referral,Circulatory,Circulatory,Diabetes